export default {
    USERS_GET_REQUEST:"USERS_GET_REQUEST",
    USERS_GET_RECEIVE:"USERS_GET_RECEIVE",
    USERS_GET_ERROR:"USERS_GET_ERROR",

    USER_POST_REQUEST:"USERS_GET_REQUEST",
    USERS_POST_RECEIVE:"USERS_GET_RECEIVE",
    USERS_POST_ERROR:"USERS_GET_ERROR",

    USERS_UPDATE_REQUEST:"USERS_UPDATE_REQUEST",
    USERS_UPDATE_RECEIVE:"USERS_UPDATE_RECEIVE",
    USERS_UPDATE_ERROR:"USERS_UPDATE_ERROR",


}